# Generated by Django 5.2.16 on 2026-10-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Web Development', 'Web Development'), ('AI & Machine Learning', 'AI & Machine Learning'), ('IoT', 'IoT'), ('Database', 'Database'), ('Other', 'Other')], max_length=100)),
                ('technologies', models.TextField(help_text='Enter technologies separated by commas.')),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('In Development', 'In Development'), ('Prototype', 'Prototype'), ('Planned', 'Planned')], default='In Development', max_length=50)),
                ('progress', models.PositiveIntegerField(default=0, help_text='Enter project progress from 0 to 100.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('github_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
