# Generated by Django 5.2.16 on 2026-10-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreativeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Photography', 'Photography'), ('Graphic Design', 'Graphic Design'), ('UI/UX Design', 'UI/UX Design'), ('Multimedia', 'Multimedia'), ('Other', 'Other')], max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='creative/')),
                ('tools', models.CharField(blank=True, help_text='Enter tools used, separated by commas.', max_length=255)),
                ('project_url', models.URLField(blank=True)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
